/**
 * Seed data awal platform (hanya baca; persistensi ada di db.js + localStorage).
 * Koleksi: users, categories, courses, modules.
 */
var DEFAULT_APP_DATA = {
  categories: [
    { id: 1, name: "Pemrograman", slug: "pemrograman" },
    { id: 2, name: "Desain & UI", slug: "desain-ui" },
    { id: 3, name: "Bisnis & Produk", slug: "bisnis-produk" },
  ],
  users: [
    {
      id: 1,
      name: "Admin Demo",
      email: "admin@elearn.demo",
      role: "admin",
      password: "demo-only",
    },
    {
      id: 2,
      name: "Dewi Lestari",
      email: "dewi@mentor.demo",
      role: "instructor",
      password: "demo-only",
    },
    {
      id: 3,
      name: "Andi Pratama",
      email: "andi@mentor.demo",
      role: "instructor",
      password: "demo-only",
    },
    {
      id: 4,
      name: "Rina Kusuma",
      email: "rina@email.demo",
      role: "student",
      password: "demo-only",
    },
  ],
  courses: [
    {
      id: 1,
      title: "Dasar Pemrograman Web",
      slug: "dasar-pemrograman-web",
      instructorId: 2,
      categoryId: 1,
      price: 199000,
      badge: "Populer",
      status: "published",
      featured: true,
      moduleMeta: "12 modul",
    },
    {
      id: 2,
      title: "Desain UI untuk Pemula",
      slug: "desain-ui-untuk-pemula",
      instructorId: 2,
      categoryId: 2,
      price: 249000,
      badge: "Baru",
      status: "published",
      featured: true,
      moduleMeta: "8 modul",
    },
    {
      id: 3,
      title: "Manajemen Produk Digital",
      slug: "manajemen-produk-digital",
      instructorId: 3,
      categoryId: 3,
      price: 299000,
      badge: "Unggulan",
      status: "published",
      featured: true,
      moduleMeta: "10 modul",
    },
    {
      id: 4,
      title: "Workshop UI Mobile",
      slug: "workshop-ui-mobile",
      instructorId: 2,
      categoryId: 2,
      price: 189000,
      badge: "Draft",
      status: "draft",
      featured: false,
      moduleMeta: "6 modul",
    },
  ],
  modules: [
    {
      id: 101,
      courseId: 1,
      order: 1,
      title: "Perkenalan & alur belajar",
      type: "video",
      durationLabel: "08:00",
    },
    {
      id: 102,
      courseId: 1,
      order: 2,
      title: "HTML semantik",
      type: "video",
      durationLabel: "22:00",
    },
    {
      id: 103,
      courseId: 1,
      order: 3,
      title: "Latihan struktur halaman",
      type: "tugas",
      durationLabel: "—",
    },
    {
      id: 201,
      courseId: 2,
      order: 1,
      title: "Prinsip hierarki visual",
      type: "video",
      durationLabel: "14:00",
    },
    {
      id: 202,
      courseId: 2,
      order: 2,
      title: "Spacing & grid sederhana",
      type: "video",
      durationLabel: "18:00",
    },
    {
      id: 301,
      courseId: 3,
      order: 1,
      title: "Problem discovery",
      type: "video",
      durationLabel: "16:00",
    },
    {
      id: 302,
      courseId: 3,
      order: 2,
      title: "Roadmap produk",
      type: "video",
      durationLabel: "20:00",
    },
  ],
};
